name: unitary_tests
on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:11.14
        env:
          POSTGRES_PASSWORD: postgres
        ports: ["5432:5432"]
        options: >-
          --mount type=tmpfs,destination=/var/lib/postgresql/data
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Run migrations
        env:
          RAILS_ENV: test
        run: |
          cp config/database.yml.github config/database.yml
          bundle exec bin/rails db:drop db:create db:migrate

      - name: Upload coverage to Codecov
        run: bash <(curl -s https://codecov.io/bash)
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
          
      - name: Run tests with RSpec
        env:
          RAILS_ENV: test
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        run: bundle exec rspec
